language: python
sudo: false
cache:
  pip: true
python:
- '2.7'
install:
- pip install six
- pip install -U -r requirements.txt
- pip install codacy-coverage
script:
- echo "not running anything really, this is just a test"
